dist: trusty
sudo: required

language: node_js

node_js:
  - '8'

cache: yarn

notifications:
  email: false

addons:
  chrome: stable

before_install:
  - "export CHROME_BIN=chromium-browser"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - npm run test
  - npm run build

after_success:
  - ./scripts/deploy.sh
